"""schema inicial Atena v1.0

Revision ID: 426e3f3a8c1e
Revises: 
Create Date: 2026-08-09 18:50:44.756678
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = '426e3f3a8c1e'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('membros',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('discord_id', sa.BigInteger(), nullable=True),
    sa.Column('whatsapp_e164', sa.String(length=20), nullable=True),
    sa.Column('nome_exibicao', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=254), nullable=True),
    sa.Column('cargo_slug', sa.String(length=32), nullable=False),
    sa.Column('xp', sa.Integer(), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('desativado_em', sa.DateTime(timezone=True), nullable=True),
    sa.Column('dracmas', sa.Integer(), nullable=False),
    sa.Column('carteira_atualizada_em', sa.DateTime(timezone=True), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('discord_id IS NOT NULL OR whatsapp_e164 IS NOT NULL', name=op.f('ck_membros_ao_menos_um_canal')),
    sa.CheckConstraint('xp >= 0', name=op.f('ck_membros_xp_nao_negativo')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_membros'))
    )
    with op.batch_alter_table('membros', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_membros_cargo_slug'), ['cargo_slug'], unique=False)
        batch_op.create_index(batch_op.f('ix_membros_discord_id'), ['discord_id'], unique=True)
        batch_op.create_index('ix_membros_ranking', ['ativo', 'xp'], unique=False)
        batch_op.create_index(batch_op.f('ix_membros_whatsapp_e164'), ['whatsapp_e164'], unique=True)

    op.create_table('webhook_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('origem', sa.String(length=40), nullable=False),
    sa.Column('evento_id', sa.String(length=128), nullable=False),
    sa.Column('tipo_evento', sa.String(length=80), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('processado', sa.Boolean(), nullable=False),
    sa.Column('erro', sa.Text(), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_webhook_events')),
    sa.UniqueConstraint('origem', 'evento_id', name='evento_unico')
    )
    with op.batch_alter_table('webhook_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_webhook_events_criado_em'), ['criado_em'], unique=False)

    op.create_table('agendamentos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.Enum('reuniao', 'evento', name='tipoagendamento', native_enum=False, length=16), nullable=False),
    sa.Column('status', sa.Enum('agendado', 'cancelado', 'concluido', name='statusagendamento', native_enum=False, length=16), nullable=False),
    sa.Column('titulo', sa.String(length=160), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('local', sa.String(length=200), nullable=True),
    sa.Column('inicio_em', sa.DateTime(timezone=True), nullable=False),
    sa.Column('fim_em', sa.DateTime(timezone=True), nullable=True),
    sa.Column('organizador_id', sa.Integer(), nullable=False),
    sa.Column('guild_id', sa.BigInteger(), nullable=True),
    sa.Column('canal_anuncio_id', sa.BigInteger(), nullable=True),
    sa.Column('mensagem_anuncio_id', sa.BigInteger(), nullable=True),
    sa.Column('google_event_id', sa.String(length=200), nullable=True),
    sa.Column('google_sincronizado_em', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancelado_em', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancelado_por_id', sa.Integer(), nullable=True),
    sa.Column('motivo_cancelamento', sa.String(length=500), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('fim_em IS NULL OR fim_em > inicio_em', name=op.f('ck_agendamentos_intervalo_valido')),
    sa.ForeignKeyConstraint(['cancelado_por_id'], ['membros.id'], name=op.f('fk_agendamentos_cancelado_por_id_membros')),
    sa.ForeignKeyConstraint(['organizador_id'], ['membros.id'], name=op.f('fk_agendamentos_organizador_id_membros'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_agendamentos'))
    )
    with op.batch_alter_table('agendamentos', schema=None) as batch_op:
        batch_op.create_index('ix_agendamentos_agenda', ['tipo', 'status', 'inicio_em'], unique=False)
        batch_op.create_index(batch_op.f('ix_agendamentos_google_event_id'), ['google_event_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_agendamentos_guild_id'), ['guild_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_agendamentos_inicio_em'), ['inicio_em'], unique=False)
        batch_op.create_index(batch_op.f('ix_agendamentos_organizador_id'), ['organizador_id'], unique=False)

    op.create_table('audit_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('acao', sa.String(length=64), nullable=False),
    sa.Column('origem', sa.Enum('discord', 'whatsapp', 'api', 'sistema', name='origemacao', native_enum=False, length=16), nullable=False),
    sa.Column('ator_id', sa.Integer(), nullable=True),
    sa.Column('ator_descricao', sa.String(length=120), nullable=False),
    sa.Column('alvo_tipo', sa.String(length=40), nullable=True),
    sa.Column('alvo_id', sa.String(length=64), nullable=True),
    sa.Column('resumo', sa.String(length=500), nullable=False),
    sa.Column('dados', sa.JSON(), nullable=True),
    sa.Column('guild_id', sa.BigInteger(), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['ator_id'], ['membros.id'], name=op.f('fk_audit_log_ator_id_membros')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_log'))
    )
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.create_index('ix_audit_log_acao_data', ['acao', 'criado_em'], unique=False)
        batch_op.create_index('ix_audit_log_alvo', ['alvo_tipo', 'alvo_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_log_ator_id'), ['ator_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_log_criado_em'), ['criado_em'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_log_guild_id'), ['guild_id'], unique=False)

    op.create_table('promocoes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('membro_id', sa.Integer(), nullable=False),
    sa.Column('cargo_anterior', sa.String(length=32), nullable=False),
    sa.Column('cargo_novo', sa.String(length=32), nullable=False),
    sa.Column('xp_no_momento', sa.Integer(), nullable=False),
    sa.Column('automatica', sa.Boolean(), nullable=False),
    sa.Column('autor_descricao', sa.String(length=120), nullable=False),
    sa.Column('motivo', sa.String(length=500), nullable=False),
    sa.Column('sincronizado_discord', sa.Boolean(), nullable=False),
    sa.Column('erro_sincronizacao', sa.Text(), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['membro_id'], ['membros.id'], name=op.f('fk_promocoes_membro_id_membros'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_promocoes'))
    )
    with op.batch_alter_table('promocoes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_promocoes_criado_em'), ['criado_em'], unique=False)
        batch_op.create_index('ix_promocoes_membro_data', ['membro_id', 'criado_em'], unique=False)
        batch_op.create_index(batch_op.f('ix_promocoes_membro_id'), ['membro_id'], unique=False)

    op.create_table('xp_audit',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('membro_id', sa.Integer(), nullable=False),
    sa.Column('autor_id', sa.Integer(), nullable=True),
    sa.Column('autor_descricao', sa.String(length=120), nullable=False),
    sa.Column('tipo', sa.Enum('concessao', 'remocao', name='tipomovimentacaoxp', native_enum=False, length=16), nullable=False),
    sa.Column('quantidade', sa.Integer(), nullable=False),
    sa.Column('saldo_anterior', sa.Integer(), nullable=False),
    sa.Column('saldo_posterior', sa.Integer(), nullable=False),
    sa.Column('motivo', sa.String(length=500), nullable=False),
    sa.Column('origem', sa.Enum('discord', 'whatsapp', 'api', 'sistema', name='origemacao', native_enum=False, length=16), nullable=False),
    sa.Column('guild_id', sa.BigInteger(), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('length(trim(motivo)) > 0', name=op.f('ck_xp_audit_motivo_obrigatorio')),
    sa.CheckConstraint('quantidade <> 0', name=op.f('ck_xp_audit_quantidade_nao_nula')),
    sa.ForeignKeyConstraint(['autor_id'], ['membros.id'], name=op.f('fk_xp_audit_autor_id_membros'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['membro_id'], ['membros.id'], name=op.f('fk_xp_audit_membro_id_membros'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_xp_audit'))
    )
    with op.batch_alter_table('xp_audit', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_xp_audit_autor_id'), ['autor_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_xp_audit_criado_em'), ['criado_em'], unique=False)
        batch_op.create_index(batch_op.f('ix_xp_audit_guild_id'), ['guild_id'], unique=False)
        batch_op.create_index('ix_xp_audit_membro_data', ['membro_id', 'criado_em'], unique=False)
        batch_op.create_index(batch_op.f('ix_xp_audit_membro_id'), ['membro_id'], unique=False)

    op.create_table('presencas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('agendamento_id', sa.Integer(), nullable=False),
    sa.Column('membro_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('pendente', 'confirmado', 'recusado', name='statuspresenca', native_enum=False, length=16), nullable=False),
    sa.Column('respondido_em', sa.DateTime(timezone=True), nullable=True),
    sa.Column('observacao', sa.String(length=300), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['agendamento_id'], ['agendamentos.id'], name=op.f('fk_presencas_agendamento_id_agendamentos'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['membro_id'], ['membros.id'], name=op.f('fk_presencas_membro_id_membros'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_presencas')),
    sa.UniqueConstraint('agendamento_id', 'membro_id', name='convite_unico')
    )
    with op.batch_alter_table('presencas', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_presencas_agendamento_id'), ['agendamento_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_presencas_membro_id'), ['membro_id'], unique=False)
        batch_op.create_index('ix_presencas_status', ['agendamento_id', 'status'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('presencas', schema=None) as batch_op:
        batch_op.drop_index('ix_presencas_status')
        batch_op.drop_index(batch_op.f('ix_presencas_membro_id'))
        batch_op.drop_index(batch_op.f('ix_presencas_agendamento_id'))

    op.drop_table('presencas')
    with op.batch_alter_table('xp_audit', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_xp_audit_membro_id'))
        batch_op.drop_index('ix_xp_audit_membro_data')
        batch_op.drop_index(batch_op.f('ix_xp_audit_guild_id'))
        batch_op.drop_index(batch_op.f('ix_xp_audit_criado_em'))
        batch_op.drop_index(batch_op.f('ix_xp_audit_autor_id'))

    op.drop_table('xp_audit')
    with op.batch_alter_table('promocoes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_promocoes_membro_id'))
        batch_op.drop_index('ix_promocoes_membro_data')
        batch_op.drop_index(batch_op.f('ix_promocoes_criado_em'))

    op.drop_table('promocoes')
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_log_guild_id'))
        batch_op.drop_index(batch_op.f('ix_audit_log_criado_em'))
        batch_op.drop_index(batch_op.f('ix_audit_log_ator_id'))
        batch_op.drop_index('ix_audit_log_alvo')
        batch_op.drop_index('ix_audit_log_acao_data')

    op.drop_table('audit_log')
    with op.batch_alter_table('agendamentos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_agendamentos_organizador_id'))
        batch_op.drop_index(batch_op.f('ix_agendamentos_inicio_em'))
        batch_op.drop_index(batch_op.f('ix_agendamentos_guild_id'))
        batch_op.drop_index(batch_op.f('ix_agendamentos_google_event_id'))
        batch_op.drop_index('ix_agendamentos_agenda')

    op.drop_table('agendamentos')
    with op.batch_alter_table('webhook_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_webhook_events_criado_em'))

    op.drop_table('webhook_events')
    with op.batch_alter_table('membros', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_membros_whatsapp_e164'))
        batch_op.drop_index('ix_membros_ranking')
        batch_op.drop_index(batch_op.f('ix_membros_discord_id'))
        batch_op.drop_index(batch_op.f('ix_membros_cargo_slug'))

    op.drop_table('membros')
    # ### end Alembic commands ###
